[build]
   builder = "nixpacks"

   [deploy]
   startCommand = "node index.js"
   restartPolicyMaxRetries = 5

   [[services]]
   name = "mock-test-backend"
   processingType = "web"
   numReplicas = 1

     [services.envVariables]
     NODE_ENV = "production"
     PORT = 5000